version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vue3-node-app
    ports:
      - "80:5173"
    volumes:  
      - ./src:/app/src
      - ./package.json:/app/package.json